### ISSUE TITLE
AMRFinderPlus annotations

### ISSUE THREAD

**Issue by missuse** [oschwengers/bakta#112]
Hi oschwengers,

first of all I wanted to thank you for bakta.
I am a first time user (as of today), evaluating to see if I should switch from dfast.
So far it appears to work great.

I have a question which stems from inexperience.

After running bakta in the log I can observe:

INFO - EXPERT-AMRFINDER - found=13

I would like to inspect them more closely but I am unsure how to extract them from the tsv/gff files.

My question boils down to, what specific annotation do the genes annotated with AMRfinder have?

Thanks and all the best,

Milan

**Comment by oschwengers** [comment]
Hi @missuse , thanks for trying bakta and reaching out!
Both TSV and GFF3 files, only contain gene symbols, product descriptions and DbXrefs since both formats get a little bit messy much more information is provided.

For a detailed list of all potentially interesting information, Bakta also provides a JSON file. Here's an example of our GCF_000008865.2 test genome:
```
"expert": {
                "amrfinder": {
                    "rank": 95,
                    "gene": "espX1",
                    "product": "type III secretion system effector EspX1",
                    "method": "BLASTP",
                    "query_cov": 1.0,
                    "model_cov": 1.0,
                    "identity": 0.9979,
                    "db_xrefs": [
                        "NCBIProtein:ADD54679.1"
                    ]
                },

```
This is all information that Bakta internally has available from AMRFinder. For TSV, GFF3, EMBL and GenBank, Bakta exports the gene symbol, product and DbXref.

To extract information from all genes annotated via AMRFinder, you could just grep for the `NCBIProtein` DbXref annotation: `grep NCBIProtein annotation.tsv`

I hope this helps. Best regards!

**Comment by missuse** [comment]
Thanks for the prompt response. This solves my problem completely!

I will just add additional info  from https://www.ncbi.nlm.nih.gov/pathogens
based on the data provided in the json.

Not sure why I skipped the json file, after all it is the largest.


All the best,

Milan
