### ISSUE TITLE
use ARMFIDER_DB env var to locate armfinder databases

### ISSUE THREAD

**Issue by EricDeveaud** [oschwengers/bakta#136]
Hello

armfinder can use n environnement variable to locate the armfinder database.

I think it would be a good idea if `bakta/utils.py` can use this one to in order to locate the database
this will avoid the need of duplication of amrfinder databases if it's already installed and configured.

best regards

Eric

**Comment by oschwengers** [comment]
Hi @EricDeveaud ,
thanks for pointing out. Yes, it shouldn't be much of an issue. Do you ask because of the duplicated db or because of an existing installation that is regularly updated? I'm asking because the AMRFinder db is a mere 200 Mb of a total of 59 Gb of the Bakta db. So disk storage shouldn't be no problem.

**Comment by EricDeveaud** [comment]
Hello, 

my first concern is. to have bakta and amrfinder installation as independant as possible.
amrfinder db update is handled automaticaly in our setup. I don't want to have divergence in the db content that may implies divergence in the results.

currently I may have the following setup 
bakta -> amrfinderdb (version N)
amrfinder -> amrfinder (version N+1) 

as for coding `avoid duplication as much s possible`
NB using symbolic links will be a no way for me ;-)

I think using native information//capabilities from the external tool your code calls wil be a good idea.

NB `bakta/expert/amrfinder.py` will also gain from using `AMRFINDER_DB`environnement variable

regards

Eric

**Comment by oschwengers** [comment]
Hi @EricDeveaud, coming back to this. Due to some recent breaking changes in the AMRFinder db (and there might be more to come) I tend to stick to the idea of a distinct AMRFinder DB instance for the Bakta installation. I know, that a duplicated DB instance is not an optimal solution, but favorable in terms of compatibility between different Bakta, AMRFinder and related DB versions. Given the small size (~200 Mb) of the AMRFinder DB compared to Bakta's ~59 Gb, I think this is OK.

Nevertheless, thanks a lot for reaching out and the heads-up.
Best regards!
