### ISSUE TITLE
Bakta takes longer on cluster when running multiple simultaneous jobs?

### ISSUE THREAD

**Issue by cizydorczyk** [oschwengers/bakta#158]
Less of a bug and more of a question.

When running Bakta on a slurm-based cluster, I find it takes longer when I submit, say, 20 jobs, in comparison to running a single job. I was wondering if this may have anything to do with access to the db, since all jobs access the same copy of the db?

From my rough estimates, it takes ~20 minutes to run a single job, but up to ~90 minutes/job when submitting ~60 jobs (each running on a separate node). I am annotating S. aureus isolates (~2.7Mbp genome size).

Is this expected behavior? Admittedly, I am not overly familiar with clusters and not sure why this might be the case. The jobs all appear to complete successfully based on their logs, but I was not expecting the increase in time/job.

Thanks,
Conrad

**Comment by oschwengers** [comment]
Hi @cizydorczyk, yes, indeed this is a huge increase in runtime and I wouldn't expect it at least not to that extent. To some extent, an increase in overall runtime is normal because the SQLite database causes a lot of I/O. If this is stored on attached network storage like for example in a SLURM system, it might take a while to serve all this I/O. However, a decent storage system should be able to handle these very little requests in a more acceptable amount of time. We also regularly use Bakta on our SLURM cluster backed by a CEPH storage system, and we see runtimes between 10 and 20 min.

**Comment by cizydorczyk** [comment]
Hmm I suppose this is an issue with my cluster then -- admittedly, I am not aware what storage system they use (and will now find out).

Thank you!
