### ISSUE TITLE
Expert systems' ranking criteria

### ISSUE THREAD

**Issue by bcpd** [oschwengers/bakta#164]
Hello -

I need help interpreting the ranking systems. The relevant Supplementary note reads:
"To give precedence on more precise annotations in case of multiple
annotations, these different sources are given a rank taking into account *proprietary* priority
levels"
- Do these priority levels incorporate identity/coverage levels? If that's not the case, do the numbers represent a semi-quantitative scale?
- Related to the above, how should the AMRFinderPlus annotation ranks be interpreted (the rank often has a score of 95)

Thanks very much.

**Comment by oschwengers** [comment]
Thanks @bcpd for this question. With *proprietary* priority levels we refer to the fact that external annotation sources exhibit varying levels of sensitivity and specificity - both internally and compared to each other. This means, that for example, NCBI BlastRules come with their own "levels of trust", i.e. `BlastRuleEquivalog`, `BlastRuleException`, `BlastRuleIS`, `BlastRuleExact`. These must be compared with and ranked against competing hits from other sources as for example VFDB. To order these hits from varying "expert annotation systems" with different models from different sources, we implemented a simple ranking system attaching a rank to each expert system and where applicable also for internal sources. Therefore, these are no semi-quantitative but qualitative scales and might be subject to future amendments if required.

We attached a fixed very high rank of `95` to AMRFinderPlus since we're highly convinced by the quality of its models and annotations.

I close this for now. Please, do not hesitate to re-open it if you have any further questions.

**Comment by bcpd** [comment]
Thank you for the very informative reply.
