### ISSUE TITLE
include tRNA isotype in annotation

### ISSUE THREAD

**Issue by acvill** [oschwengers/bakta#170]
If possible, it would be nice for tRNA annotations in gff3 files to include the isotype / anticodon. Something like `product=tRNA-Arg(cct)` in the attribute column instead of just `product=tRNA-Arg`. This could be implemented by including an option to allow users to favor Aragorn annotations of tRNA over tRNAscan-SE. It seems like bakta only uses Aragorn for tmRNA annotation, by default. Prokka uses Aragorn for tRNA annotation and includes the anticodon in the output gff.

**Comment by oschwengers** [comment]
Hi @acvill , thanks for reaching out and this suggestion. Acutally, I'd like to stick to tRNAscan-SE, because it also predicts pseudo-tRNAs. BUT, we could easily add the anticodon information w/o replacing tRNAscan-SE by Aragorn, since tRNAscan-SE also provides this.

Just to get it right, could you please elaborate a little bit more on your usecase? Do you need this in the `product` or could the anticodon also be provided as a distinct GFF3 attribute? This way, we could harmonize the GFF3 output with those of INSDC (Genbank and EMBL) which have a distinct qualifier for this: `/anticodon=(pos:228747..228749,aa:Ile,seq:gat)`.

**Comment by acvill** [comment]
I'm generally interested in tRNA use as it relates to codon bias, so it would be helpful to have information on the anticodon sequences without running a secondary annotation. The anticodon could be a distinct attribute; it does not need to be part of the `product`. 

Thanks for creating and maintaining bakta, @oschwengers !

**Comment by oschwengers** [comment]
Hi @acvill , this is now active (https://github.com/oschwengers/bakta/commit/43f92f81f75d786e29b36cabddd44fde968b17fc) and will be public in the upcoming `1.6.0` release. I'll hope this fits your needs and close this for now.
Best regards!
