### ISSUE TITLE
PNG circos plot legend

### ISSUE THREAD

**Issue by Arkadiy-Garber** [oschwengers/bakta#182]
Hi, thanks for a great tool.

I am just wondering about he circular genome plot from Circos that is created. There are several layers/circles that are created with different colors, and I was wondering whether there is a legend, or a document that explains what the colors mean?

Thanks!
Arkadiy

**Comment by oschwengers** [comment]
@Arkadiy-Garber I hope your question is answered? I'll close this for now but please, do not hesitate to re-open it in any case.
Best regards!

**Comment by Arkadiy-Garber** [comment]
Hey, sorry for the silence. Thanks for that description. Yes that makes sense!

**Comment by splaisan** [comment]
sorry to ask but I did not create circos for a long while and fear w<i will spend quite some time doingthis.
it would be just great to have a separate legend box picture created using the same color codes as in the used config and the descriptions added to the doc, so that we can add it to a plot externally when needed and rescale it as wished. 
A circos conf file would be enough, the user can then plot it with a single circos call.
The plots are nice but hard to read without a legend
