### ISSUE TITLE
BlastRules and VFDB hits are not displayed at the same time.

### ISSUE THREAD

**Issue by davidtong28** [oschwengers/bakta#198]
Hi Oliver,
I also noticed that `BlastRules:` was added to the Dbxref in the latest version. Previously I wasn't aware of it because there were no hints telling me a gene is a BlastRules hit. I was confused why it does not show up in the `gff3` files so good thing to know now.
Forgive me if I'm wrong: having looked at the new annotation files, it seems like no genes are annotated by both databases. My guess is that Blastrules and VFDB is combined into a single database, so the Expert search only searches once and reports the best hit. Previously I was wondering why some of my genes (that are in VFDB) does not get annotated as a VFDB hit. After the new version I found those genes got annotated as Blastrules instead. 
I was wondering if the top hits in both databases could be reported in Dbxref if possible. 
Also I'm curious what version of VFDB is Bakta using (Core or Full)?

Cheers,
David

**Comment by oschwengers** [comment]
Hi David,
Bakta uses the core set of experimentally verified proteins of VFDB.

Regarding the hits, Bakta incorporates VFDB and NCBI BlastRules as expert proteins. Since BlastRules itself has an internal ranking and we somehow need to decide which hit will be used within an annotation, we ranked all BlastRules internal ranks and VFDB entries ourselves.

Here's a list of all Ranks:
- NCBI BlastRuleEquivalog: 70
- VFDB: 75
- NCBI BlastRuleException: 80
- NCBI BlastRuleIS: 95
- NCBI BlastRuleExact: 99

User provided proteins are ranked 100. The higher these numbers, the higher the priority.

For the `GFF3` (and all other standardized file formats) we should stick to the final annotation that has been assigned. If there's a need for *all* hits, the `JSON` file can be parsed which contains all the information Bakta has come along during the entire annotation process.

**Comment by davidtong28** [comment]
Thanks for answering.
I looked into the `JSON` files. It seems like the `"expert_proteins":` section of each gene still only records the highest rank rather than all ranks. Was it intended to record all ranks?
I'm asking because I think it is important to keep my annotations consistent. Also the `dbxref` of the VFDB hits contain VFC number which is very handy to classify the virulence factors based on their functions.

Thank you!

David

**Comment by davidtong28** [comment]
That sounds good. Thank you and I'm looking forward to the new release.

David

**Comment by oschwengers** [comment]
@davidtong28 This is now available in https://github.com/oschwengers/bakta/releases/tag/v1.8.1
