### ISSUE TITLE
Small User Improvements for Bakta

### ISSUE THREAD

**Issue by Dx-wmc** [oschwengers/bakta#200]
Hi Oliver, 

I recently started using Bakta, which is an excellent annotation software. Although it is slightly slower than Prokka, I find its accuracy comparable to that of PGAP. However, I think there are a couple of areas where improvements could be made.

Firstly, the output cds locus tags are not numbered consecutively but in groups of five. I don't quite understand the current numbering system, and I would prefer it to be changed to a coherent sequential numbering system like the one used in Prokka.

Secondly, I would suggest adding a "--force" parameter (like in Prokka) to the Bakta options. By default, Bakta overwrites the output folder, which may not be ideal in all cases. Providing multiple options can better prevent misoperation.

Lastly, the SVG file format output only displays a simple circular graphic. It would be useful to have a user-defined output format that allows for the selection of specific genes of interest.

I hope this helps!

Dave

**Comment by oschwengers** [comment]
Dear Dave, thanks for your suggestions.

1. We use an increment of 5 by purpose, so that there is some free space for additional later locus tags in case one need to manually add features.
2. Yes, this is something I also thought about. I'll put it on my list and add this to the list for the next release.
3. Also something I already have on my list. Nothing too complex, it's just a larger implementation part. I have this in my backlog list for "somewhen" ;-)

Thanks and best regards!

**Comment by oschwengers** [comment]
I've introduced a `--force` parameter as suggested in 2.: https://github.com/oschwengers/bakta/commit/70eab662064c303fb4dd4fc313800380a5087f86

**Comment by Dx-wmc** [comment]
Great job! I hope to see more useful functions added in the future.
