### ISSUE TITLE
different result comparing to prokka

### ISSUE THREAD

**Issue by zzsunday** [oschwengers/bakta#235]
hello,  something strange happens.
when I use prokka(prokka version 1.14.6) to annotate,  the result showed that the position from 49243  to 50055 is entire CDS. but, when I using bakta( bakta version 1.7.0) ,  it truncate the entire CDS into two different CDS.  I also do it by blast, the result showed that the 49243  to 50055 100% match to a specific gene. 

attached files is :
prokka.gff : prokka result
bakta.gff : bakta result
ndm5.out: blastn result
19D44.fasta: sequence to annotate(query sequence)
ndm5.fasta: the ndm5 gene sequence
[Archive.zip](https://github.com/oschwengers/bakta/files/12505887/Archive.zip)

**Comment by oschwengers** [comment]
Hi @zzsunday, this is the case because Prokka und Bakta usedifferent gene prediction tools. Prokka uses Prodigal whereas Bakta uses Pyrodigal - a successor to Prodigal which has a few bugs fixed and thus produces slightly different gene predictions as described in https://github.com/althonos/pyrodigal/issues/42

I hope I could answer your question and close this for now. Please, do not hesitate to re-open it in any case.
