### ISSUE TITLE
MacOS M2 cannot install bakta using conda.

### ISSUE THREAD

**Issue by YuLanSky** [oschwengers/bakta#261]
**Describe the bug**
When I was using my old computer (macOS Intel chip), Bakta ran smoothly. However, I recently upgraded to a new computer with an M2 chip and found that I cannot install Bakta using conda. 

The reason is that conda cannot find the piler-cr package in any channel. 

When I searched for the piler-cr package in the bioconda database, I found that it only supports Linux-64 and OSX-64 (Intel), so it cannot be installed.

My question is: M1/M2 chips have been around for a while now, so I was wondering how others are running Bakta on M1/M2 chip computers? Thank you

```
(H) ➜  ~ micromamba install bakta
bioconda/osx-arm64                                          Using cache
bioconda/noarch                                             Using cache
conda-forge/osx-arm64                                       Using cache
conda-forge/noarch                                          Using cache
pkgs/main/osx-arm64                                           No change
pkgs/r/osx-arm64                                              No change
pkgs/r/noarch                                                 No change
pkgs/main/noarch                                              No change
error    libmamba Could not solve for environment specs
    The following package could not be installed
    └─ bakta is not installable because it requires
       └─ piler-cr, which does not exist (perhaps a missing channel).
critical libmamba Could not solve for environment specs
```

**Comment by oschwengers** [comment]
Hi @YuLanSky ,
thanks for reaching out and asking. I guess, this is rather a general issue with still lacking support for M1/M2 in Bioconda. Hence, may I kindly refer you to the Bioconda GH repository: https://github.com/bioconda/bioconda-recipes/

Until there is a general upstream fix for that and if your analyses do not depend on CRISPR arrays, you could build your own Conda environment for Bakta w/o Piler-CR and then skip this step in Bakta via `--skip-crispr`. 
Since I do not have a Mac do not know about Bioconda's potential M1/M2 support route,  I'm very sorry that I cannot provide more support in this case. But I'm pretty sure that many people are interest in that and that Bioconda maintainers can give more answers. 

Best regards
Oliver
