### ISSUE TITLE
Inquiry on CDS annotation

### ISSUE THREAD

**Issue by songmj86** [oschwengers/bakta#296]
Hi

I do not have any bugs on Bakta, but I got a question to ask CDS annotation

I have thousands of prodigal-generated CDS and use it as inputs (Not genome, but GENE ! ) for Bakta annotation

Is it okay to get the appropriate results if I use "-skip-CDS" ?

Thanks !

**Comment by oschwengers** [comment]
Hi,
thanks for asking. There's a dedicated command `bakta_proteins` for this sort of bulk annotation. However, this is not implemented on a gene but protein level, so you have to provide the translated protein sequences instead of the nucleic CDS sequences. Please find more information on this here: https://github.com/oschwengers/bakta#protein-bulk-annotation

**Comment by songmj86** [comment]
Oh. Thanks !
