### ISSUE TITLE
A question on "qc: revised sequence:" and the use of " --regions"

### ISSUE THREAD

**Issue by augustkx** [oschwengers/bakta#353]
Hi, 

May I ask what is the purpose of the following step? Why assign new id to the original ID? 
Does it shuffle the order only when I use multiple threads?

Thanks in advance!

> 12:31:55.004 - INFO - UTILS - qc: revised sequence: id=contig_1906, orig-id=contig_312, type=contig, complete=False, topology=linear, name=, description='[gcode=11] [topology=linear]', orig-description=''

**Comment by augustkx** [comment]
If I need to use `--regions` , do I need to provide the contig sequence at the end of the gff file?
If so, shall I only provide the relevant contig sequences, or shall I provide all the contig sequences? For example, I only know a CDS in a contig, while the sample has 10 contigs.

**Comment by oschwengers** [comment]
Hi thanks for reaching out with this. let me answer in order:

1. Existing assemblers use varying sequence id schema thus creating different and sometimes odd sequence IDEs. To streamline these, Bakta provides its own standardized set of sequence IDs. If this is not intentional, you can keep original sequence IDs via `--keep-contig-headers` or provide your own IDs/names via `--replicons`
2. No. Bakta neither requires nor uses sequences provided in the `gff3` since all features in it must match the provided assembly that is provided to Bakta as `fasta` anyway. So, in your case, you only need to provide the coordinates of your known CDS as `gff3`.
