### ISSUE TITLE
CDS prediction but not annotation option

### ISSUE THREAD

**Issue by PedroMTQ** [oschwengers/bakta#74]
Dear all,
Thank you for developing this tool, it looks very comprehensive and the documentation is really thorough.
I went through your documentation and I see you already have an option `--skip-cds` where you can skip CDS prediction and annotation. However, I was wondering if it would be possible to have the option to still have the CDS prediction but to skip the posterior CDS functional annotation. 
This is simply because I'd like to use an alternative protein function annotation tool but would still need to have the CDS.
In this regard, if you do add this option, which DBs would not be necessary?

Thanks and regards,
Pedro

**Comment by oschwengers** [comment]
Hi @PedroMTQ ,
I see your point here but you could simply take the CDS protein or nucleotide sequences from the `.faa`/`.ffn` files and use them with any external annotation tool of your choice. Might that be a way to go?
Of course you could also just use Prodigal to predict CDS sequences, however in this case you would miss the sORF sequences extracted by Bakta.

**Comment by PedroMTQ** [comment]
Hi @oschwengers ,
Yes I could do that, but isn't Bakta also doing CDS functional annotation?  I'd just like to skip that step (just to minimize runtime)  while preserving all other Bakta's features. If implementing such a feature is inconvenient, I could of course do as you said.

Thanks and regards,
Pedro

**Comment by oschwengers** [comment]
sure, Bakta uses Prodigal for the regional prediction and then conducts several subsequent steps for the functional annotation (sequence identification and homology searches with subsequent lookup of pre-assigned annotations as well as expert annotation systems).
Implementing another skipping option should be possible. However, I'd like to keep the usage as small/simple as possible and I'm not yet quite sure if this is a larger use case. Therefore, I'll leave this open just in case that more users might ask for such a feature - otherwise I kindly ask to use the CDS sequences as suggested above.

Thanks for reaching out!
