### ISSUE TITLE
adding sequence at the end of gff3 (similar to prokka gff output)

### ISSUE THREAD

**Issue by onertipaday** [oschwengers/bakta#75]
First of all:, thanks for this great tool.
I was wondering if would be feasible to add  the fasta sequence at the end of the gff3 file (similarly to prokka gff output). It would be useful for downstream analysis (e.g. roary pangenome pipelines.). Thanks for your effort.
Paolo

**Comment by oschwengers** [comment]
Hi, 
yes, that's possible. Just run Bakta in normal mode and all genome sequences should be written at the end of the `gff3` files. 

However, running in `--compliant` mode Bakta does not write genome sequences to `gff3` file ends as otherwise NCBI's `table2asn_GFF` tool keeps complaining and writing warning messages.

**Comment by onertipaday** [comment]
Thanks so much!
