### ISSUE TITLE
option --complete doesn't seem to work?

### ISSUE THREAD

**Issue by stefanielagers** [oschwengers/bakta#86]
When I use the option --complete the log file still says complete=False . If I also provide a .tsv file (by the way a .tsv file is NOT the same as a .csv file!) where I specify topology circular it seems to work and it changes to complete=True.

**Comment by oschwengers** [comment]
Hi,
unfortunately, based on the information provided, I cannot reproduce this error using version `1.2.4`. Setting the `--complete` flag alone (w/o a replicon table) is properly logged and used as intended.

Hence, could you elaborate a bit more on:
- which version did you use?
- which installation procedure have you used: Conda, Pip, Docker, ...?
- the *exact* command line that has been executed (log file, 3rd line)
- potentially the log file itself (best using the `--verbose` flag)
- the replicon metadata table


> (by the way a .tsv file is NOT the same as a .csv file!)

Thanks for the hint ;-) Did that cause any confusion? You can provide the replicon metadata table in both formats `TSV` and `CSV` as for example:
- https://raw.githubusercontent.com/oschwengers/bakta/main/test/data/replicons.csv
- https://raw.githubusercontent.com/oschwengers/bakta/main/test/data/replicons.tsv

**Comment by stefanielagers** [comment]
You are correct, it's the FASTA - imported: line that says complete=False, which confuses, but later on it says INFO - UTILS - qc:  complete=True, topology=circular. So it should treat it as complete and circular.

The problem with .csv files is that if they are generated in Excel, the separator used will depend on the regional settings, so it can be either comma or semicolon, and the latter apparently doesn't work!

**Comment by oschwengers** [comment]
> You are correct, it's the FASTA - imported: line that says complete=False, which confuses, but later on it says INFO - UTILS - qc: complete=True, topology=circular. So it should treat it as complete and circular.

The first log refers to the import of the raw sequence, the second on the revised (qc) contig properties. Indeed, the first log message provides no useful information and is rather confusing. I've amended the log message in the commit mentioned above.


> The problem with .csv files is that if they are generated in Excel, the separator used will depend on the regional settings, so it can be either comma or semicolon, and the latter apparently doesn't work!

Yes, that's true. However, this peculiarity is related to Excel and user's choice how to export this. It's a common standard that a `CSV`, _i.e._ comma separated values, uses a `,` instead of `;` which is not (yet) supported by Bakta. If more users stumble over this we might add support for this in an upcoming release but for now, I'd kindly ask you to use either a `TSV` or a proper `CSV` in it's most basic form.
